[package]
name = "icdo3-extractor"
version = "0.1.0"
edition = "2024"

[dependencies]
pdf-extract = "0.6.0" # For extracting text from PDFs
regex = "1.10.2"      # For pattern matching
csv = "1.3.0"         # For writing CSV files
